server:
  port: 80

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - uri: lb://authentication
        predicates:
        - Path=/authentication/**
      - uri: lb://documents
        predicates:
        - Path=/documents/**
      - uri: lb://users
        predicates:
        - Path=/users/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters: 
      - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"

  security:
    oauth2:
      resourceserver:
        jwt:
          issuerUri: http://localhost:8080/auth/realms/master
          #issuerUri: http://localhost:31002/auth/realms/master
          
#Usar la instrumentacion de Sleuth
  #sleuth:
   # reactor:
    #  instrumentation-type: decorate-on-each
      
#Conectarse con el servidor de Zipkin
  #zipkin:
   # base-url: http://localhost:9411
    
#Register in Eureka Server
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka:8761/eureka
  instance:
    preferIpAddress: true
      