server:
  port: 31003

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      - id: users
        uri: lb://users
        predicates:
          - Path=/api/v1/user/**
      default-filters: 
      - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:31002/auth/realms/master
          
#Register in Eureka Server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:31001/eureka
    register-with-eureka: true